# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Creating CodeBuild container build runs
      - for CONTAINER in $CONTAINERS_PATH/*/;
        do
        echo $CONTAINER;
        aws codebuild start-build --project-name=$CONTAINER_PROJECT_NAME --environment-variables-override name=IMAGE_REPO_NAME,value=$STACK_PREFIX-$(basename $CONTAINER),type=PLAINTEXT name=BUILD_CONTEXT,value=$CONTAINER,type=PLAINTEXT;
        done
  post_build:
    commands:
      - echo Build completed on `date`
