name: ESMFold
description: "This workflow predicts the three-dimensional structure of a protein from its amino acid sequence using the ESM large language model from Facebook AI Research."
engine: WDL
main: main.wdl
parameterTemplate:
  fasta_path:
    description: "Input file in FASTA format. Only single-chain inputs are supported at this time."
    optional: false
  max_length:
    description: "maximum amino acid length of target (default: 800)"
    optional: true
  aws_region:
    description: "AWS region (e.g. us-east-1). must match were source data is located and where workflow is executed"
    optional: true
  esmfold_model_parameters:
    description: "S3 path to esmfold model parameters"
    optional: true
storageCapacity: 1200
tags:
  Name: 'ESMFold'
accelerators: GPU