name: ESMFold
description: "This workflow predicts the three-dimensional structure of a protein from its amino acid sequence using the ESM large language model from Facebook AI Research."
engine: WDL
definitionZip: fileb://workflows/esmfold/workflow.zip
main: main.wdl
parameterTemplate:
  fasta_path:
    description: "Input file in FASTA format. Only single-chain inputs are supported at this time."
    optional: false
  max_length:
    description: "maximum amino acid length of target (default: 800)"
    optional: true
  ecr_registry:
    description: "Ecr registry for container images (e.g. <account-id>.dkr.ecr.<region>.amazonaws.com"
    optional: false
  aws_region:
    description: "AWS region (e.g. us-east-1). must match were source data is located and where workflow is executed"
    optional: false
storageCapacity: 1200
tags:
  Name: 'ESMFold'
accelerators: GPU