# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Creating CodeBuild build runs
      - for SRC in $ARTIFACTS_PATH/*/;
        do
        echo $SRC;
        aws codebuild start-build --project-name=$PROJECT_NAME --environment-variables-override name=NAME,value=$STACK_PREFIX-$(basename $SRC),type=PLAINTEXT name=BUILD_CONTEXT,value=$SRC,type=PLAINTEXT;
        done
  post_build:
    commands:
      - echo Build completed on `date`
